project_name: "Default Threat Status Assessment"
project_description: "Extracts regional conservation status for species based on standard IUCN codes."

# Define the specific pieces of data you want to extract for each species.
data_fields:
  - name: "statusCodeVerbatim"
    description: "The REGIONAL conservation status. This is often a two-letter code. DO NOT confuse with the 'Global status'. Preferably use IUCN codes. If text mentions multiple threat assessments, extract the latest regional iucn based categories."
    validation_values: ["RE", "CR", "EN", "VU", "NT", "LC", "DD", "NF"]
  - name: "statusCriteria"
    description: "The criteria codes (e.g., A2c, B1ab(iii,v), C2a(i)) used in the regional assessment. Extract them exactly as written. If none are present, return 'NF'."
# Optional: You can override the default prompts here if needed.
# If these are commented out or removed, the system will use its internal default prompts.
# prompts:
#   text_based: |
#     <Your custom text prompt here, using {species_name}, {text_chunk}, and {data_fields_schema} placeholders>
#   image_based: |
#     <Your custom image prompt here, using {species_name} and {data_fields_schema} placeholders>